# Generated by Django 4.0.4 on 2022-08-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('user', models.CharField(max_length=16, verbose_name='user')),
                ('DOB', models.DateField(verbose_name='DOB')),
                ('gender', models.CharField(max_length=6, verbose_name='gender')),
            ],
        ),
        migrations.DeleteModel(
            name='employees',
        ),
    ]
